import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { ensureAgentWorktree, inspectRepository } from '../src/repository.mjs';
import { initGitRepo } from '../test-support/helpers.mjs';

test('repository inspection gates non-git folders and prepares isolated agent worktrees', async (t) => {
  const base = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'workpets-repository-'));
  const repo = path.join(base, 'repo');
  const plain = path.join(base, 'plain');
  await fs.promises.mkdir(plain);
  t.after(() => fs.promises.rm(base, { recursive: true, force: true }));
  assert.equal((await inspectRepository(plain)).valid, false);
  await fs.promises.mkdir(repo);
  await initGitRepo(repo);
  const inspected = await inspectRepository(repo);
  assert.equal(inspected.valid, true);
  assert.equal(inspected.branch, 'main');
  assert.ok(inspected.commits.length >= 1);
  const previous = process.env.WORKPETS_WORKTREE_ROOT;
  process.env.WORKPETS_WORKTREE_ROOT = path.join(base, 'worktrees');
  t.after(() => { if (previous === undefined) delete process.env.WORKPETS_WORKTREE_ROOT; else process.env.WORKPETS_WORKTREE_ROOT = previous; });
  const prepared = await ensureAgentWorktree(repo, { id: 'agent_12345678', name: 'Frontend Dev' });
  assert.equal(prepared.created, true);
  assert.equal(fs.existsSync(path.join(prepared.path, '.git')), true);
  assert.equal(prepared.branch, 'workpets/agent_12345678');
  assert.equal((await ensureAgentWorktree(repo, { id: 'agent_12345678', name: 'Frontend Dev' })).created, false);
});
